name = "MCSR (Fabric)"
author = "sukarodo / uchks"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73cc08308f08b9038ec860c217f0e24d0f8b1947cae6db804424165e50e7ed4c"

[versions]
fabric = "0.14.19"
minecraft = "1.16.1"
